name       : libcdio
version    : 2.0.0
release    : 6
source     :
    - https://ftp.gnu.org/gnu/libcdio/libcdio-2.0.0.tar.gz : 1b481b5da009bea31db875805665974e2fc568e2b2afa516f4036733657cf958
homepage   : https://www.gnu.org/software/libcdio/
license    : GPL-2.0
component  : multimedia.library
summary    : A library to encapsulate CD-ROM reading and control
description: |
    This library provides an interface for CD-ROM access. It can be used by applications that need OS- and device-independent access to CD-ROM devices.
builddeps  :
    - pkgconfig(libcddb)
setup      : |
    %patch -p1 < $pkgfiles/libcdio-0.83-linking.patch
    %reconfigure --disable-static --disable-rpath
build      : |
    %make
install    : |
    %make_install

    # remove the architecture information from version.h
    sed -i -e "s|${version//./\\.}.*$|${version}\\\"|g" $installdir/usr/include/cdio/version.h
    # remove the source build path from cdio_config.h
    sed -i "/LIBCDIO_SOURCE_PATH/s|.*|/* #undef LIBCDIO_SOURCE_PATH */|" $installdir/usr/include/cdio/cdio_config.h
check      : |
    %make check
